### ISSUE TITLE
Errors using coc & ncm2_d on freebsd 13

### ISSUE THREAD

**Issue by devosalain** [ncm2/ncm2-d#7]
[coc.nvim]: UnhandledRejection: write EPIPE
Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:164:15)
    at writeGeneric (node:internal/stream_base_commons:155:3)
    at Socket._writeGeneric (node:net:795:11)
    at Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:390:12)
    at _write (node:internal/streams/writable:331:10)
    at Socket.Writable.write (node:internal/streams/writable:335:10)
    at /usr/home/x/.local/share/nvim/plugged/coc.nvim/build/index.js:36:3107
    at new Promise (<anonymous>)
    at mA.write (/usr/home/x/.local/share/nvim/plugged/coc.nvim/build/index.js:36:3028)
[ncm2_d_dcd@yarp] Process Process-1:
[ncm2_d_dcd@yarp]   File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run

After 20 errors neovim starts...

FreeBSD 13.1-RELEASE releng/13.1
Python 3.9.12
neovim-0.6.1_1    
npm-node17-8.5.2 
node-17.0.1

**Comment by viniarck** [comment]
Hi @devosalain, I'm not sure if this should work with coc, also I'm not actively maintaining this plugin anymore. Feel free to send a PR if you're interested in using this plugin though, you're welcome.
